language: python
python:
  - "3.5"
before_install: "rm -f data-test.sqlite"
install: "pip install -r requirements.txt -r test-requirements.txt"
script: tox -e cover
notifications:
  email:
    recipients:
      - hieulq19@gmail.com
    on_success: change
on_failure: always