language: python
python:
  - "3.5"
install: "pip install -r requirements.txt"
script: tox -e cover
notifications:
  email:
    recipients:
      - hieulq19@gmail.com
    on_success: change
on_failure: always